# tasks_config.yaml

tasks:
  - name: example_task
    type: composite
    schedule:
      type: interval
      args:
        hours: 24
    steps:
      - name: check_file_exists
        type: function
        function: check_file_exists
        args:
          file_path: "path/to/file.txt"
      - name: run_command
        type: subprocess
        command: ["echo", "Running Task"]
        run_if: check_file_exists.result
      - name: wait_for_condition
        type: wait
        max_wait_time: 300  # 5 minutes
        check_interval: 10  # Every 10 seconds
        condition:
          type: custom_condition
          args:
            parameter: "some_value"
      - name: update_file
        type: function
        function: update_last_run
        args:
          file_path: "path/to/last_run.txt"

functions:
  check_file_exists:
    path: "./utils.py"
    function: check_file_exists
  custom_condition:
    path: "./utils.py"
    function: custom_condition
  update_last_run:
    path: "./utils.py"
    function: update_last_run